matrix:
    include:
      - language: python
        python: 3.8
        services: postgresql
        beforeScript:
          - pip install -r requirements.txt
          - psql -c 'create database superSchool;' -U postgres
          - psql -c 'create role balvernaz with password bulldog';' -U postgres
        script:
          - pytest
        
