matrix:
    include:
      - language: python
        python: 3.8
        services: postgresql
        beforeScript:
          - pip install -r requirements.txt
          - psql -c 'create database superSchool;' -U postgres
          - createuser -s balvernaz
        script:
          - pytest
      - language: nodejs
        nodejs: 12.8
        cache:
         directories:
           - node_modules
        before_install:
          - npm update
        install:
          - npm install
        script:
          - npm test