matrix:
    include:
      - language: python
        python: 3.8
        beforeScript:
          - source venv/bin/activate
          - pip install -r requirements.txt
        script:
          - ptw -n